In [2]:
import numpy as np
import skfuzzy
from sklearn import datasets
from sklearn.metrics import confusion_matrix

## Fuzzy C-means

In [3]:
# Inportando base de dados
iris = datasets.load_iris()

In [4]:
# Executando algoritimo
r = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005, maxiter = 1000, init = None)

In [5]:
# Probabilidades
previsoes_porcentagem = r[1]
previsoes_porcentagem

array([[1.07192159e-03, 7.50149977e-03, 6.41687501e-03, 1.01121923e-02,
        1.76789063e-03, 2.06277956e-02, 6.50693219e-03, 1.41270899e-04,
        2.19112337e-02, 5.34425616e-03, 1.02043903e-02, 2.43243511e-03,
        9.18117111e-03, 2.52443336e-02, 3.76422019e-02, 5.43217379e-02,
        1.75007806e-02, 1.05882702e-03, 3.03194755e-02, 6.65563069e-03,
        9.54513091e-03, 4.79551253e-03, 1.38361369e-02, 6.11576243e-03,
        9.84388994e-03, 7.97805057e-03, 1.57467067e-03, 2.08740489e-03,
        1.99646882e-03, 6.28591558e-03, 6.47712693e-03, 7.94309894e-03,
        2.03400203e-02, 3.23575418e-02, 4.59653592e-03, 4.80653574e-03,
        1.15676894e-02, 2.92683981e-03, 1.92397726e-02, 5.33482130e-04,
        1.68828592e-03, 4.70111664e-02, 1.52138731e-02, 6.33294169e-03,
        1.66084287e-02, 8.63557864e-03, 7.36738802e-03, 8.13002382e-03,
        7.26182689e-03, 9.19558666e-04, 5.01734218e-01, 2.07395326e-01,
        6.00687116e-01, 8.03381015e-02, 2.17855021e-01, 2.047193

In [6]:
# Verificando probabilidade dos registros 0, 1 e 2
previsoes_porcentagem[0][0]

0.0010719215858711955

In [7]:
previsoes_porcentagem[1][0]

0.996623633881423

In [8]:
previsoes_porcentagem[2][0]

0.002304444532705633

In [9]:
# Verificando probabilidade de um registro pertencer a cada um dos cluster (o somatório é 1.0 que indica 100%)
for x in range(150):
    print(previsoes_porcentagem[0][x], previsoes_porcentagem[1][x], previsoes_porcentagem[2][x])

0.0010719215858711955 0.996623633881423 0.002304444532705633
0.007501499766022816 0.9758383262120485 0.016660174021928632
0.006416875012992238 0.9798166593699735 0.01376646561703411
0.01011219233026249 0.9674086141874562 0.022479193482281324
0.0017678906298364315 0.9944700147244566 0.003762094645706882
0.020627795586603957 0.9345436956363564 0.044828508777039665
0.006506932194884059 0.9794820442013789 0.014011023603737153
0.0001412708992992498 0.9995470040969763 0.0003117250037245905
0.021911233691056964 0.9303439239232522 0.04774484238569103
0.005344256159837631 0.9827122334703517 0.011943510369810707
0.010204390337251791 0.9680290452614899 0.02176656440125829
0.0024324351143304155 0.9921318396356841 0.005435725249985431
0.009181171114145821 0.9706240270092873 0.020194801876567033
0.0252443336073337 0.9229373234282705 0.05181834296439588
0.037642201925090865 0.8897238754192127 0.07263392265569649
0.05432173789632203 0.8412954730309998 0.1043827890726782
0.01750078056340693 0.946906512

In [10]:
# Verificando previsões de acordo com a maior porcentagem atribuida
previsoes = previsoes_porcentagem.argmax(axis = 0)
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [11]:
# Gerando matriz de confusão
confusao = confusion_matrix(iris.target, previsoes)
confusao

array([[ 0, 50,  0],
       [ 3,  0, 47],
       [37,  0, 13]])