In [1]:
import numpy as np
import skfuzzy
from sklearn import datasets
from sklearn.metrics import confusion_matrix

## Fuzzy C-means

In [2]:
# Inportando base de dados
iris = datasets.load_iris()

In [3]:
# Executando algoritimo
r = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005, maxiter = 1000, init = None)

In [5]:
# Probabilidades
previsoes_porcentagem = r[1]
previsoes_porcentagem

array([[2.30445169e-03, 1.66614650e-02, 1.37673085e-02, 2.24809079e-02,
        3.76214035e-03, 4.48311998e-02, 1.40118958e-02, 3.11748362e-04,
        4.77481164e-02, 1.19444831e-02, 2.17677497e-02, 5.43620253e-03,
        2.01962693e-02, 5.18212732e-02, 7.26368844e-02, 1.04386857e-01,
        3.55943520e-02, 2.28891927e-03, 6.55916664e-02, 1.41638705e-02,
        2.18715596e-02, 1.03786474e-02, 2.75198679e-02, 1.44754319e-02,
        2.32626567e-02, 1.84743635e-02, 3.58552918e-03, 4.56737823e-03,
        4.32993133e-03, 1.42125084e-02, 1.48112783e-02, 1.77080465e-02,
        4.11625770e-02, 6.35063501e-02, 1.03491389e-02, 1.02059851e-02,
        2.42629902e-02, 6.18403834e-03, 4.11078240e-02, 1.17851217e-03,
        3.58432004e-03, 1.02330605e-01, 3.21945106e-02, 1.43939809e-02,
        3.81543814e-02, 1.92360913e-02, 1.58501052e-02, 1.76634333e-02,
        1.55276247e-02, 2.00914803e-03, 4.53623631e-01, 7.63330931e-01,
        3.67974927e-01, 8.70449096e-01, 7.57911034e-01, 9.737925

In [6]:
# Verificando probabilidade dos registros 0, 1 e 2
previsoes_porcentagem[0][0]

0.002304451685498655

In [7]:
previsoes_porcentagem[1][0]

0.9966236411149497

In [8]:
previsoes_porcentagem[2][0]

0.0010719071995516313

In [9]:
# Verificando probabilidade de um registro pertencer a cada um dos cluster (o somatório é 1.0 que indica 100%)
for x in range(150):
    print(previsoes_porcentagem[0][x], previsoes_porcentagem[1][x], previsoes_porcentagem[2][x])

0.002304451685498655 0.9966236411149497 0.0010719071995516313
0.016661464957690678 0.9758366085319599 0.0075019265103496695
0.0137673085071247 0.9798155414020957 0.006417150090779756
0.02248090793720268 0.9674063390571022 0.010112753005695141
0.0037621403493320513 0.9944699755552745 0.0017678840953933993
0.04483119975307822 0.9345400298386847 0.020628770408236987
0.014011895795811625 0.9794808828181648 0.0065072213860236225
0.00031174836213642836 0.9995469727756929 0.00014127886217069887
0.04774811636767414 0.9303395929412097 0.021912290691116037
0.011944483131131778 0.9827109367888812 0.005344580079987079
0.021767749720823473 0.9680274477206656 0.010204802558510915
0.005436202527462033 0.9921311966646597 0.0024326008078783363
0.020196269328166268 0.9706220795188882 0.009181651152945452
0.05182127321706047 0.9229333937051797 0.02524533307775992
0.07263688440438948 0.8897196533461947 0.037643462249415845
0.1043868571296156 0.8412895129052649 0.054323629965119496
0.03559435201876406 0.94

In [10]:
# Verificando previsões de acordo com a maior porcentagem atribuida
previsoes = previsoes_porcentagem.argmax(axis = 0)
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [11]:
# Gerando matriz de confusão
confusao = confusion_matrix(iris.target, previsoes)
confusao

array([[ 0, 50,  0],
       [47,  0,  3],
       [13,  0, 37]])